name: integration-test

on:
  push:
    branches:
      - main
  pull_request:

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.9.0
        with:
          distribution: 'zulu'
          java-version: 19

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: integration test
        id: integration-test
        run: |
          cd include-build
          ./gradlew roborazzi-gradle-plugin:check --stacktrace

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-reports
          path: include-build/roborazzi-gradle-plugin/build/reports
          retention-days: 30

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-test-results
          path: include-build/roborazzi-gradle-plugin/build/test-results
          retention-days: 30
